### ISSUE TITLE
Mouse controls

### ISSUE THREAD

**Issue by robhawkes** [UDST/vizicities#11]
Overall implementation of mouse controls. Individual elements of this feature have their own issues.

---
- [x] View panning using mouse – #13
- [x] View tilt using mouse – #14 
- [x] View rotation using mouse – #15 
- [x] View zoom using mouse – #16
- [ ] Write tests for mouse controls – #12
