### ISSUE TITLE
Load features using vector tiles

### ISSUE THREAD

**Issue by robhawkes** [UDST/vizicities#20]
Overall implementation for loading features using vector tiles in either GeoJSON or Protobuf format. Individual elements of this feature have their own issues.

Resources and notes [can be found on the wiki](https://github.com/robhawkes/vizicities/wiki/Vector-tiles).

---
- [x] Load features from OSM Overpass API – #24
- [x] Load features using tile-based grid system – #25
- [ ] Cache loaded tiles – #23 
- [ ] Write tests for vector tiles – #26
